import 'package:flutter/material.dart';

import 'achievement.dart';

/// Catálogo CENTRAL de logros. Los `id` son estables (no cambiar nunca).
/// Añadir logros nuevos = añadir entradas; nunca reutilizar un id.
const List<Achievement> kAchievementsCatalog = [
  // ── Distancia ───────────────────────────────────────────────────────────────
  Achievement(
    id: 'distance.first_km',
    name: 'Primer kilómetro',
    description: 'Corre tu primer kilómetro.',
    category: AchievementCategory.distance,
    icon: Icons.flag_rounded,
    rarity: AchievementRarity.common,
    metric: AchievementMetric.totalKm,
    target: 1,
  ),
  Achievement(
    id: 'distance.first_5k',
    name: 'Primeros 5K',
    description: 'Completa una carrera de 5 km.',
    category: AchievementCategory.distance,
    icon: Icons.directions_run_rounded,
    rarity: AchievementRarity.common,
    metric: AchievementMetric.longestRunKm,
    target: 5,
  ),
  Achievement(
    id: 'distance.first_10k',
    name: 'Primeros 10K',
    description: 'Completa una carrera de 10 km.',
    category: AchievementCategory.distance,
    icon: Icons.directions_run_rounded,
    rarity: AchievementRarity.uncommon,
    metric: AchievementMetric.longestRunKm,
    target: 10,
  ),
  Achievement(
    id: 'distance.half_marathon',
    name: 'Media maratón',
    description: 'Completa una carrera de 21,1 km.',
    category: AchievementCategory.distance,
    icon: Icons.emoji_events_outlined,
    rarity: AchievementRarity.rare,
    metric: AchievementMetric.longestRunKm,
    target: 21.0975,
  ),
  Achievement(
    id: 'distance.marathon',
    name: 'Maratón',
    description: 'Completa una carrera de 42,2 km.',
    category: AchievementCategory.distance,
    icon: Icons.emoji_events_rounded,
    rarity: AchievementRarity.epic,
    metric: AchievementMetric.longestRunKm,
    target: 42.195,
  ),
  Achievement(
    id: 'distance.km_100',
    name: '100 km',
    description: 'Acumula 100 km en total.',
    category: AchievementCategory.distance,
    icon: Icons.speed_rounded,
    rarity: AchievementRarity.uncommon,
    metric: AchievementMetric.totalKm,
    target: 100,
  ),
  Achievement(
    id: 'distance.km_500',
    name: '500 km',
    description: 'Acumula 500 km en total.',
    category: AchievementCategory.distance,
    icon: Icons.speed_rounded,
    rarity: AchievementRarity.rare,
    metric: AchievementMetric.totalKm,
    target: 500,
  ),
  Achievement(
    id: 'distance.km_1000',
    name: '1.000 km',
    description: 'Acumula 1.000 km en total.',
    category: AchievementCategory.distance,
    icon: Icons.workspace_premium_rounded,
    rarity: AchievementRarity.epic,
    metric: AchievementMetric.totalKm,
    target: 1000,
  ),

  // ── Constancia ──────────────────────────────────────────────────────────────
  Achievement(
    id: 'consistency.first_week',
    name: 'Primera semana activa',
    description: 'Ten tu primera semana con actividad.',
    category: AchievementCategory.consistency,
    icon: Icons.calendar_today_rounded,
    rarity: AchievementRarity.common,
    metric: AchievementMetric.activeWeeks,
    target: 1,
  ),
  Achievement(
    id: 'consistency.streak_3',
    name: 'Racha de 3 días',
    description: 'Corre 3 días seguidos.',
    category: AchievementCategory.consistency,
    icon: Icons.local_fire_department_outlined,
    rarity: AchievementRarity.common,
    metric: AchievementMetric.currentStreakDays,
    target: 3,
  ),
  Achievement(
    id: 'consistency.streak_7',
    name: 'Racha de 7 días',
    description: 'Corre 7 días seguidos.',
    category: AchievementCategory.consistency,
    icon: Icons.local_fire_department_rounded,
    rarity: AchievementRarity.uncommon,
    metric: AchievementMetric.currentStreakDays,
    target: 7,
  ),
  Achievement(
    id: 'consistency.weeks_4',
    name: 'Cuatro semanas activas',
    description: 'Acumula 4 semanas con actividad.',
    category: AchievementCategory.consistency,
    icon: Icons.event_available_rounded,
    rarity: AchievementRarity.uncommon,
    metric: AchievementMetric.activeWeeks,
    target: 4,
  ),
  Achievement(
    id: 'consistency.year',
    name: 'Un año corriendo',
    description: 'Mantente activo 12 meses seguidos.',
    category: AchievementCategory.consistency,
    icon: Icons.military_tech_rounded,
    rarity: AchievementRarity.legendary,
    metric: AchievementMetric.activeMonthsInARow,
    target: 12,
  ),

  // ── Exploración ─────────────────────────────────────────────────────────────
  Achievement(
    id: 'exploration.first_street',
    name: 'Primera calle',
    description: 'Descubre tu primera calle.',
    category: AchievementCategory.exploration,
    icon: Icons.signpost_outlined,
    rarity: AchievementRarity.common,
    metric: AchievementMetric.distinctStreets,
    target: 1,
  ),
  Achievement(
    id: 'exploration.streets_100',
    name: '100 calles',
    description: 'Descubre 100 calles distintas.',
    category: AchievementCategory.exploration,
    icon: Icons.map_rounded,
    rarity: AchievementRarity.rare,
    metric: AchievementMetric.distinctStreets,
    target: 100,
  ),
  Achievement(
    id: 'exploration.first_neighborhood',
    name: 'Primer barrio',
    description: 'Explora tu primer barrio.',
    category: AchievementCategory.exploration,
    icon: Icons.holiday_village_outlined,
    rarity: AchievementRarity.common,
    metric: AchievementMetric.distinctNeighborhoods,
    target: 1,
  ),
  Achievement(
    id: 'exploration.first_city',
    name: 'Primera ciudad',
    description: 'Corre por tu primera ciudad.',
    category: AchievementCategory.exploration,
    icon: Icons.location_city_rounded,
    rarity: AchievementRarity.common,
    metric: AchievementMetric.distinctCities,
    target: 1,
  ),
  Achievement(
    id: 'exploration.cities_5',
    name: 'Cinco ciudades',
    description: 'Corre por 5 ciudades diferentes.',
    category: AchievementCategory.exploration,
    icon: Icons.travel_explore_rounded,
    rarity: AchievementRarity.epic,
    metric: AchievementMetric.distinctCities,
    target: 5,
  ),
  Achievement(
    id: 'exploration.first_country',
    name: 'País extranjero',
    description: 'Corre en un segundo país.',
    category: AchievementCategory.exploration,
    icon: Icons.public_rounded,
    rarity: AchievementRarity.legendary,
    metric: AchievementMetric.distinctCountries,
    target: 2,
  ),

  // ── Retos ───────────────────────────────────────────────────────────────────
  Achievement(
    id: 'challenges.first',
    name: 'Primer reto',
    description: 'Completa tu primer reto.',
    category: AchievementCategory.challenges,
    icon: Icons.task_alt_rounded,
    rarity: AchievementRarity.common,
    metric: AchievementMetric.challengesCompleted,
    target: 1,
  ),
  Achievement(
    id: 'challenges.ten',
    name: 'Diez retos',
    description: 'Completa 10 retos.',
    category: AchievementCategory.challenges,
    icon: Icons.checklist_rounded,
    rarity: AchievementRarity.uncommon,
    metric: AchievementMetric.challengesCompleted,
    target: 10,
  ),
  Achievement(
    id: 'challenges.fifty',
    name: 'Cincuenta retos',
    description: 'Completa 50 retos.',
    category: AchievementCategory.challenges,
    icon: Icons.verified_rounded,
    rarity: AchievementRarity.epic,
    metric: AchievementMetric.challengesCompleted,
    target: 50,
  ),
  Achievement(
    id: 'challenges.first_legendary',
    name: 'Reto legendario',
    description: 'Completa un reto legendario.',
    category: AchievementCategory.challenges,
    icon: Icons.auto_awesome_rounded,
    rarity: AchievementRarity.rare,
    metric: AchievementMetric.legendaryChallengesCompleted,
    target: 1,
  ),
  Achievement(
    id: 'challenges.monthly_sweep',
    name: 'Mes completo',
    description: 'Completa todos los retos de un mes.',
    category: AchievementCategory.challenges,
    icon: Icons.calendar_month_rounded,
    rarity: AchievementRarity.epic,
    metric: AchievementMetric.monthlyChallengeSweeps,
    target: 1,
  ),

  // ── Strava ──────────────────────────────────────────────────────────────────
  Achievement(
    id: 'strava.first_import',
    name: 'Primera importación',
    description: 'Importa tu primera actividad de Strava.',
    category: AchievementCategory.strava,
    icon: Icons.sync_rounded,
    rarity: AchievementRarity.common,
    metric: AchievementMetric.stravaImports,
    target: 1,
  ),
  Achievement(
    id: 'strava.imports_10',
    name: 'Diez importaciones',
    description: 'Importa 10 actividades de Strava.',
    category: AchievementCategory.strava,
    icon: Icons.cloud_sync_rounded,
    rarity: AchievementRarity.uncommon,
    metric: AchievementMetric.stravaImports,
    target: 10,
  ),
  Achievement(
    id: 'strava.imports_100',
    name: 'Cien importaciones',
    description: 'Importa 100 actividades de Strava.',
    category: AchievementCategory.strava,
    icon: Icons.cloud_done_rounded,
    rarity: AchievementRarity.rare,
    metric: AchievementMetric.stravaImports,
    target: 100,
  ),
  Achievement(
    id: 'strava.year',
    name: 'Un año con Strava',
    description: 'Lleva un año conectado con Strava.',
    category: AchievementCategory.strava,
    icon: Icons.link_rounded,
    rarity: AchievementRarity.epic,
    metric: AchievementMetric.stravaConnectedDays,
    target: 365,
  ),
];
