// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsKDynWKoIYJvZ8oGiBHJbOVyx-2OPVZo',
    appId: '1:756598503122:android:fd501b842c9cef10d05f0b',
    messagingSenderId: '756598503122',
    projectId: 'trazos-database',
    storageBucket: 'trazos-database.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb2xgV4w1L_mP80toB3E_W-wpegQLwit4',
    appId: '1:756598503122:ios:14a326ffd498d770d05f0b',
    messagingSenderId: '756598503122',
    projectId: 'trazos-database',
    storageBucket: 'trazos-database.firebasestorage.app',
    iosBundleId: 'com.trazos.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdrGlWsoAt_RF8vLloIzOlyDgq2VlTRGE',
    appId: '1:756598503122:web:599633eca71c88e3d05f0b',
    messagingSenderId: '756598503122',
    projectId: 'trazos-database',
    authDomain: 'trazos-database.firebaseapp.com',
    storageBucket: 'trazos-database.firebasestorage.app',
    measurementId: 'G-KMPS4DM8CC',
  );

}